name: Build
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Sample Bundle Jar
        run: ./gradlew sampleBundleJar

      - name: Build Sample Clip Jar
        run: ./gradlew sampleClipJar

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs